### ISSUE TITLE
Cannot signin

### ISSUE THREAD

**Issue by CanerKaraca23** [JonasNilson/idle_master_extended#119]
When I try to login my account, steam login page always refreshing.

**Comment by JonasNilson** [comment]
Try disabling Quick login under `File > Settings > Quick login`

**Comment by CanerKaraca23** [comment]
Worked, thanks!

**Comment by Tydir** [comment]
had the same issue, I've disabled quick login and everything works fine!

**Comment by ArthurFleao** [comment]
> This time, my account isn't saving.

Facing the same issue here, even after disabling the quick login, after the popup saying 'Idle Master is saving your information' closes, i'm still not logged in.

I noticed this pops up in the `errors.log` file:
```
24/09/2020 10:11:50   
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMaster.frmBrowser.makeSureLoginHasCompletedOrRefresh()
   at IdleMaster.frmBrowser.tmrCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
That may help solving the issue.

**Comment by JonasNilson** [comment]
In the latest version the quick-login has been reworked and is available through a button in the browser window
