### ISSUE TITLE
Login window doesnt work, worked 1 hour ago

### ISSUE THREAD

**Issue by kblade07** [JonasNilson/idle_master_extended#13]
When im trying to login, im getting the old IdleMaster login issue. The window is going away and its not asking me for the guard code. I can type any fake username or password, press login and it will happen again. What should i do?  Steam api broke the extended again?

Later edit:
If you input any steam account, real or fake, the page is gone.

If you open the login page and press Join Steam, it will show as logged in and Idle competed on my last account that worked like 2 hours ago. In the mean time, i added a family view code on that account and started idlemaster by mistake.

If i go into settings > Display advanded informations - I can see that the session login and steam login are from that account that worked last time. How can i change that? Its there a bug on the application or there is a cache bug? I redownloaded the app several times and it still goes on that account so i guess this thing is stored somewhere

I tried to delete the files in this location C:\Users\Alex\AppData\Local\IdleMaster
since i inspected the config file and everything was related to the account on which worked last time, but everytime i delete them and i unzip a new idlemaster, they appear without me attepting to login in idlemaster. Why and how can i delete them permanently because im pretty sure this can be one of the causes to the bug

Later edit 2:

Yea if i unzip a new idlemaster. open the login page and press Join Steam, it will go to the last working account datas. Session login, steam profile id and so on. How can i fix that?

And one error log when i am trying to connect to a real steam account
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMaster.frmMain.<blacklistToolStripMenuItem_Click>b__63_0(String appid)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at IdleMaster.frmMain.blacklistToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by kblade07** [comment]
I managed to connect with the browser cookies, sessionID and steamLOGIN from chrome settings. The usual login doest work at all...the page is closing when you input any account, real or false.

**Comment by anything1232** [comment]
Browser cache cleared and AppData deleted,

**The log in page does not ask for mobile authentification** and so log in fails.

Win7 64bit, IE11, dot.net (4.7.1) should be fine. And every C++ distributable from the stone age until now.

**Comment by zeichen980** [comment]
Same here, a friend tried it 3 and 2 days ago i think and everything was perfectly fine. Now I got some new games I wanted to idle myself and it doesn't work. Not at my new PC and not at my old Laptop where the IdleMaster Folder (and the AppData folder of IdleMaster) wasn't changed since the last time I tried when it worked.
Just closing right after the "Login" button is pressed. Even if both textfields are empty.

**Comment by ArcticFoxen** [comment]
its comeback, working now without any problem if u still getting problem try to clean install another location on pc.

**Comment by zeichen980** [comment]
It is indeed. Thank you for the update!

**Comment by JonasNilson** [comment]
I'm glad it solved itself.

I just gave it a try and the login seems to have changed somewhat, but works at the moment.
