### ISSUE TITLE
Login to steam failed !

### ISSUE THREAD

**Issue by MrKiyan** [JonasNilson/idle_master_extended#143]
Hello, it's more than 1 week i cant login to steam with idle master 
i tried automatic login, and also i typed
all thing i can see in error file is this 
2020-11-23 8:15:47 AM   
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMasterExtended.frmBrowser.tmrCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
2020-11-23 8:15:49 AM   
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMasterExtended.frmBrowser.tmrCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by JonasNilson** [comment]
Try the Cookie login method: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods
