### ISSUE TITLE
[Quick Login] quick login script not working anymore

### ISSUE THREAD

**Issue by raffa258** [JonasNilson/idle_master_extended#227]
the quick login script is not working anymore. it gets stuck at "login script activated". 

https://s4.uupload.ir/files/sem_título_21l.png

**Comment by Sergio6936** [comment]
Yeah same here.

**Comment by Yoti** [comment]
Same for me.

**Comment by TheRealLegend27Sheesh** [comment]
samee

**Comment by docsvs** [comment]
Same here.

**Comment by Chernoid** [comment]
I'm having the same issue. This is what "error.log" file contains for me.

`6/25/2021 3:55:53 AM   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/xxx
System.Exception: Response is null or empty. Added (+1) to RetryCount
   at IdleMasterExtended.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
   at IdleMasterExtended.frmMain.<GetBadgePageAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdleMasterExtended.frmMain.<LoadBadgesAsync>d__24.MoveNext()
6/25/2021 3:56:05 AM   
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMasterExtended.frmBrowser.tmrCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
6/25/2021 3:56:53 AM   
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMasterExtended.frmBrowser.tmrCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by MrRaf99** [comment]
Same on mine copy

**Comment by kkjguilherme** [comment]
saame

**Comment by RiCkDounKs** [comment]
Same here.

**Comment by RiCkDounKs** [comment]
Normal login is working?

**Comment by int22** [comment]
The function being used for "Quick Login" was silently removed from the steam community login page and steam client.

It can't be fixed without Valve reinstating the previously used feature or adding a new and better feature.

**Comment by CyberCreator** [comment]
Currently, the only possible way to log in is through cookies?

**Comment by int22** [comment]
> Currently, the only possible way to log in is through cookies?

@CyberCreator The current methods that work are credentials through the page or with cookies.

**Comment by JonasNilson** [comment]
The issue has been documented here for future references: https://github.com/JonasNilson/idle_master_extended/wiki/Quick-login

In short: the Steam login web page no longer support logging in using your local Steam application. They removed the JavaScript functionality: `LoginUsingSteamClient`

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
