### ISSUE TITLE
Idle Master error on Fast mode behavior

### ISSUE THREAD

**Issue by Tooloco** [JonasNilson/idle_master_extended#241]
So, im getting this error 
`System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at IdleMasterExtended.Badge.Idle()
   at IdleMasterExtended.frmMain.UpdateIdleProcesses()
   at IdleMasterExtended.frmMain.StartMultipleIdle()
   at IdleMasterExtended.frmMain.StartIdle()
   at IdleMasterExtended.frmMain.<tmrReadyToGo_Tick>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)`

When I try to idle games on fast mode. However, idling individual games seems to work fine.
`System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMasterExtended.frmBrowser.tmrCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`
I also get that error when idling individually but it seems like it continues working.

**Comment by Tooloco** [comment]
Okay so it seems like it wasn't working even though it looked like, no cards were dropped.

Nevertheless, launching as administrator has fixed the problems and it is know working properly.
