### ISSUE TITLE
Cant Sign in

### ISSUE THREAD

**Issue by MrKiyan** [JonasNilson/idle_master_extended#311]
Hello, 
Like other ppl i have the Same problem, Login button not working at all. And this is my Error file if helps

```
7/1/2022 4:16:54 AM   
System.Net.WebException: The remote name could not be resolved: 'api.github.com'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at IdleMasterExtended.frmMain.GetLatestVersion()
   at IdleMasterExtended.frmMain.frmMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
7/1/2022 4:17:04 AM   
System.Net.WebException: The remote name could not be resolved: 'api.github.com'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at IdleMasterExtended.frmMain.GetLatestVersion()
   at IdleMasterExtended.frmMain.frmMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by rar130600** [comment]
@MrKiyan Logging in with cookies works.
Guide: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods#cookies

**Comment by DryreL** [comment]
Same problem but without error log. It does not login because login button does not respond.

**Comment by JessePinkguy** [comment]
Same

**Comment by JonasNilson** [comment]
Related: https://github.com/JonasNilson/idle_master_extended/issues/307

**Comment by JonasNilson** [comment]
Try the latest release and see if it helps: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0
