### ISSUE TITLE
''The data you entered is invalid. Please try again'' . 

### ISSUE THREAD

**Issue by shiraikoocha** [JonasNilson/idle_master_extended#378]
Although I have correctly written the cookies in the program, I am getting this error and cannot log in.

However, I have also included a screenshot. As you can see on there, it looks like I am logged in to my Steam account and it says 'badge page loading. please wait.' However, even after waiting for a long time, the notification message does not change. And it doesn't log in to the account. It doesn't show my games.

Content of the 'error.log' file

1.01.2023 15:33:15   frmSettingsAdvanced -> CheckAndSave
System.NullReferenceException: Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
   konum: IdleMasterExtended.CookieClient.<IsLogined>d__7.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: IdleMasterExtended.frmSettingsAdvanced.<CheckAndSave>d__6.MoveNext()
1.01.2023 15:33:15   
System.NullReferenceException: Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
   konum: IdleMasterExtended.CookieClient.<IsLogined>d__7.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: IdleMasterExtended.frmMain.<tmrReadyToGo_Tick>d__82.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
1.01.2023 15:34:03   frmSettingsAdvanced -> CheckAndSave
System.NullReferenceException: Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
   konum: IdleMasterExtended.CookieClient.<IsLogined>d__7.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: IdleMasterExtended.frmSettingsAdvanced.<CheckAndSave>d__6.MoveNext()
1.01.2023 15:34:03   
System.NullReferenceException: Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
   konum: IdleMasterExtended.CookieClient.<IsLogined>d__7.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: IdleMasterExtended.frmMain.<tmrReadyToGo_Tick>d__82.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
![cokies Adsız](https://user-images.githubusercontent.com/121753834/210170941-559d3c33-2755-4932-be6f-e3f6e049fb70.png)
![Adsız](https://user-images.githubusercontent.com/121753834/210170943-f3ef01a2-904e-4e06-846e-7d81c4302b14.png)
![Adsız1](https://user-images.githubusercontent.com/121753834/210170944-bc57c6f4-989b-4774-be48-a607d888e903.png)
[error.log](https://github.com/JonasNilson/idle_master_extended/files/10328773/error.log)

**Comment by Ch33kiBreek1** [comment]
Its the same problem for me... However i did get the badge loading notification on older versions of Idle master... For the newer version it doesnt even let me sign in despite copying everything from the cookie addon

**Comment by shiraikoocha** [comment]
"It's the same for me. I can't drop the card in the 1.8.0 version. Are you able to drop the card?"

**Comment by jonas-med-ett-s** [comment]
I'm not entirely sure about the issue you are experiencing as I am not able to reproduce it.

It looks like the control of your cookies fails for some reason here:
https://github.com/JonasNilson/idle_master_extended/blob/43b35e5fa632838d53d374d78c4abff61a405f59/Source/IdleMasterExtended/CookieClient.cs#L105-L111

You could try and do the following:
1. [Delete all configuration files](https://github.com/JonasNilson/idle_master_extended/wiki/Delete-configuration-files)
2. [Troubleshoot cookies](https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods#troubleshooting-cookies)

**Comment by n00b42** [comment]
Tried both 1.9, 1.8
Both showed "The data you entered is invalid. Please try again"
But after closing the login/session popup both version showed to be connected with steam.
However, 1.9. would be stuck in "loading" games, while 1.8 successfully loaded the game list.

**Comment by jonas-med-ett-s** [comment]
> Tried both 1.9, 1.8
> Both showed "The data you entered is invalid. Please try again"
> But after closing the login/session popup both version showed to be connected with steam.
> However, 1.9. would be stuck in "loading" games, while 1.8 successfully loaded the game list.

I'm curious about if you get any `error.log` from 1.9?

Can you also provide more info about:
- Your operating system?
- Do you use Steam Guard? (App or email?)

The difference between 1.8 and 1.9 is pretty small so I might be able to determine what difference is causing the issue.

**Comment by n00b42** [comment]
- Windows 10
- The account in question uses SteamGuard with email

Seems to be the same error as the one posted in the issue.

1.9 `error.log`
~~~
05.01.2023 13:35:56   frmSettingsAdvanced -> CheckAndSave
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei IdleMasterExtended.CookieClient.<IsLogined>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei IdleMasterExtended.frmSettingsAdvanced.<CheckAndSave>d__6.MoveNext()
05.01.2023 13:36:43   frmSettingsAdvanced -> CheckAndSave
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei IdleMasterExtended.CookieClient.<IsLogined>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei IdleMasterExtended.frmSettingsAdvanced.<CheckAndSave>d__6.MoveNext()
05.01.2023 13:38:11   frmSettingsAdvanced -> CheckAndSave
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei IdleMasterExtended.CookieClient.<IsLogined>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei IdleMasterExtended.frmSettingsAdvanced.<CheckAndSave>d__6.MoveNext()
05.01.2023 13:39:18   
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei IdleMasterExtended.CookieClient.<IsLogined>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei IdleMasterExtended.frmMain.<tmrReadyToGo_Tick>d__82.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
~~~

1.8 `error.log`

~~~
05.01.2023 13:43:35   frmSettingsAdvanced -> CheckAndSave
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei IdleMasterExtended.CookieClient.<IsLogined>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei IdleMasterExtended.frmSettingsAdvanced.<CheckAndSave>d__6.MoveNext()
~~~

**Comment by n00b42** [comment]
Related and probably duplicate of #365, #358, #360

**Comment by shiraikoocha** [comment]
> Yeniden üretemediğim için, yaşadığınız sorundan tam olarak emin değilim.
> 
> Görünüşe göre çerezlerinizin kontrolü burada bir nedenden dolayı başarısız oluyor:
> 
> https://github.com/JonasNilson/idle_master_extended/blob/43b35e5fa632838d53d374d78c4abff61a405f59/Source/IdleMasterExtended/CookieClient.cs#L105-L111
> 
> Aşağıdakileri yapmayı deneyebilir ve yapabilirsiniz:
> 
> 1. [Tüm yapılandırma dosyalarını sil](https://github.com/JonasNilson/idle_master_extended/wiki/Delete-configuration-files)
> 2. [Çerez sorunlarını giderme](https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods#troubleshooting-cookies)

I had already deleted the configuration files before, but it didn't offer a solution. When I tried to log in to my second Steam account, the 'steamMachineAuth' cookie seemed to be unique and when I put it in the required place, I was able to log in to the account smoothly. But after that, I couldn't see the 'steamMachineAuth' cookie again. Both of my accounts are protected by Steam Guard on my phone. Later, I opened two more accounts, which were automatically protected by email, but I couldn't log in to these accounts due to the same problem. In total, I get this error in 3 out of 4 accounts. Disabling Steam Guard did not make any difference.

**Comment by shiraikoocha** [comment]
> Hem 1.9 hem de 1.8 denedim Her ikisi de "Girdiğiniz veriler geçersiz. Lütfen tekrar deneyin" mesajı verdi. Ancak oturum açma/oturum açılır penceresini kapattıktan sonra her iki sürümün de steam ile bağlantılı olduğu görüldü. Ancak 1.9. 1.8 oyun listesini başarıyla yüklerken oyunların "yüklenmesinde" takılıp kalırdı.

The same situation applies to me.

**Comment by n00b42** [comment]
Seems related to the SteamGuard method. Was able to test it with a SteamApp SteamGuard account and 1.9. worked without an issue.

**Comment by seriousfreezing** [comment]
The same thing happens to me, I put in the correct data and Idle says it's wrong

**Comment by iomihai** [comment]
I had the same issue, using the cookies from a browser signed in a long time ago.
v1.9 logged in but was not getting the list of games and 1.10 said login data was invalid.
I signed in incognito mode into steam using the phone QR method and used those cookies, 1.10 was able to sign in and start idling.
v1.10 Log when having the issue
```
31.03.2023 23:29:48   CookieClient -> WebResponse = System.Net.HttpWebRequest
System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at IdleMasterExtended.CookieClient.GetWebResponse(WebRequest request, IAsyncResult result)
31.03.2023 23:29:48   CookieClient -> GetHttpAsync, for url = https://steamcommunity.com/profiles/REDACTED
System.Net.WebException: An exception occurred during a WebClient request. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.WebClient.DownloadBitsState.SetResponse(WebResponse response)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdleMasterExtended.CookieClient.<GetHttpAsync>d__3.MoveNext()
```

**Comment by emacor23** [comment]
Hello, I also have the same problem, is there a solution?

**Comment by P3drix** [comment]
i have the same prob, and i try all i see and dont work..
![aaaaaaaaa](https://github.com/JonasNilson/idle_master_extended/assets/46261431/de11de43-9174-4714-b6b8-f44cae7585e7)

**Comment by ardxyzfnbr** [comment]
yo guys its little bit late but better than never right? you can try fetching the sessionid and SteamLoginSecure from a different page, such as your main profile page
