### ISSUE TITLE
[BUG] Idle Master doesn't work properly if it can't download a game banner

### ISSUE THREAD

**Issue by montoner0** [JonasNilson/idle_master_extended#481]
## Describe the bug ##
When there's an issue with downloading `http://cdn.akamai.steamstatic.com/steam/apps/<appid>/header_292x136.jpg` pictures then the application behaves inconsistently. Its UI freezes, steam-idle.exe crashes, no real idling occurs.

## To Reproduce ##
1. Simulate issues with cdn.akamai.steamstatic.com (e. g. block with a firewall or with the hosts file)
1. Start Idle Master and start idling
1. Notice that background processes for steam-idle.exe are crashing in ~45 seconds after the start

## Expected behavior ##
Issue with the picture downloading doesn't prevent idling or freeze UI

## Error logs ##
```
Sat 24/08/2024 17:46:10   frmMain -> StartIdle -> load pic, for id = xxxxx
System.Net.WebException: The operation has timed out
   at System.Net.WebClient.OpenRead(Uri address)
   at System.Net.WebClient.OpenRead(String address)
   at System.Windows.Forms.PictureBox.Load()
   at System.Windows.Forms.PictureBox.Load(String url)
   at IdleMasterExtended.frmMain.StartSoloIdle(Badge badge)
```
Also the Application log in the Event Viewer has these .NET runtime errors:
```
Application: steam-idle.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.WebClient.OpenRead(System.Uri)
   at System.Net.WebClient.OpenRead(System.String)
   at System.Windows.Forms.PictureBox.Load()
   at System.Windows.Forms.PictureBox.Load(System.String)
   at steam_idle.frmMain..ctor(Int64)
   at steam_idle.Program.Main(System.String[])
```

**Comment by revanmj** [comment]
Currently seems to occur with Oblivion Remastered
