### ISSUE TITLE
Idle Master Extended v1.5 keeps logging me out

### ISSUE THREAD

**Issue by fury014** [JonasNilson/idle_master_extended#87]
Everytime i leave it on idleing it just logs me out after around 15/20mins. Thanks.

**Comment by JonasNilson** [comment]
Do you get any `error.log` in your Idle Master Extended directory? If so, please see if you get a correlating error when the logging out happens.

**Comment by fury014** [comment]
Sorry for the late response. Well nothing happens, it just logs out and then i need to log back in and it still logs out x number of times in a day.

**Comment by JonasNilson** [comment]
I believe I managed to recreate the issue, and had this in my `error.log`:
```
2020-07-12 20:36:53   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/<id>
System.Exception: Response is null or empty. Added (+1) to RetryCount
   at IdleMaster.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
   at IdleMaster.frmMain.<GetBadgePageAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__32.MoveNext()
2020-07-12 21:13:06   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/<id>
System.Exception: Response is null or empty. Added (+1) to RetryCount
   at IdleMaster.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
   at IdleMaster.frmMain.<GetBadgePageAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__32.MoveNext()
```

I guess I have to look into the issue to see exactly when the issue appears.

**Comment by fury014** [comment]
Yep, thats the same one

**Comment by JonasNilson** [comment]
You could try to insert your cookie data from your browser and see if it helps: https://github.com/JonasNilson/idle_master_extended/issues/27#issuecomment-577597720

**Comment by jhonsp101** [comment]
Hi Jonas, i have the same problem, v1.5 keeps logging me out. i don't know if i have any error.log and i don't know how to insert cookie data from browser. I would appreciate if you could help me. Thanks

**Comment by LoganTRowley** [comment]
Also having this issue. Here's my error log:

9/7/2020 12:26:53 AM   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/76561198091552395
System.Exception: Response is null or empty. Added (+1) to RetryCount
   at IdleMaster.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
   at IdleMaster.frmMain.<GetBadgePageAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__32.MoveNext()
9/7/2020 1:45:57 AM   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/76561198091552395
System.Exception: Response is null or empty. Added (+1) to RetryCount
   at IdleMaster.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
   at IdleMaster.frmMain.<GetBadgePageAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__32.MoveNext()
9/7/2020 3:40:06 AM   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/76561198091552395
System.Exception: Response is null or empty. Added (+1) to RetryCount
   at IdleMaster.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
   at IdleMaster.frmMain.<GetBadgePageAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__32.MoveNext()
